/**
 * Auto-generated API implementations
 * This file is automatically generated based on your API dependencies.
 * Do not edit manually - changes will be overwritten.
 */

import { Agent } from '@greaseclaw/workflow-sdk';

/**
 * Task status type
 */
export type TaskStatus = 'waiting' | 'running' | 'succeeded' | 'failed';

/**
 * Execution result returned by all API calls
 */
export interface ExecutionResult {
  success: boolean;
  error?: string;
  task?: {
    id: string;
    status: TaskStatus;
    extract_data?: string;
    metrics_tokens: number;
    metrics_time: number;
  };
}

/**
 * WorkflowApis interface - methods generated from your API dependencies
 */
export interface WorkflowApis {
  www_1688_com_get_sku_list_from_ur_0fuwor: (product_url: string) => Promise<ExecutionResult>;
  buyin_jinritemai_com_get_douyin_product_d_o2bup6: () => Promise<ExecutionResult>;
}


/**
 * Creates API client using agent.call()
 */
export function createWorkflowApis(agent: Agent): WorkflowApis {
  return {
  /**
   * Get Sku List From Url
   * 获取商品数组，每一项包含商品名字、价格和库存数。
   * @endpoint /v1/custom/www-1688-com-get-sku-list-from-ur-0fuwor
   */
  async www_1688_com_get_sku_list_from_ur_0fuwor(product_url: string): Promise<ExecutionResult> {
    const { data } = await agent.call<ExecutionResult>('/v1/custom/www-1688-com-get-sku-list-from-ur-0fuwor', {
      method: 'POST',
      body: { product_url },
    });
    return data;
  },

  /**
   * Get Douyin Product Data
   * 获取抖音商品数据
   * @endpoint /v1/custom/buyin-jinritemai-com-get-douyin-product-d-o2bup6
   */
  async buyin_jinritemai_com_get_douyin_product_d_o2bup6(): Promise<ExecutionResult> {
    const { data } = await agent.call<ExecutionResult>('/v1/custom/buyin-jinritemai-com-get-douyin-product-d-o2bup6', {
      method: 'POST',
    });
    return data;
  },
  };
}
